name: user_repository
description: Dart package which manage the user domain.
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  equatable: ^1.2.6
  meta: ^1.2.4
  shared_preferences: ^0.5.12+4