name: authentication_repository
description: Dart package which manage authentication.
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.2.6
  shared_preferences: ^0.5.12+4