name: authentication_repository
description: Dart package which manage authentication.
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  http: ^0.13.0
  meta: ^1.2.6
  shared_preferences: ^2.0.0
